version: '3'

services: 
   erddap:
      build: .
      image: erddap_dev:2.02
      container_name: erddap
      restart: always
      ports:
         - "8888:8080/tcp"
         - "8883:8443"
         - "8889:8009"
      volumes:
         - ./erddap.war:/usr/local/tomcat8/webapps/erddap.war
         - ./data:/usr/local/tomcat8/data
         - ./content:/usr/local/tomcat8/content
