version: '3'

services: 
   erddap:
      build: .
      image: erddap_dev:2.02
      restart: always
      ports:
         - "8888:8080"
         - "8883:8443"
         - "8889:8009"
      volumes:
         - "./tomcat8:/usr/local/tomcat8"
         - "./doc:/usr/local/tomcat8/doc"
